import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
process.chdir(fileURLToPath(new URL('..', import.meta.url)));
const icons = {};
for (const file of readdirSync('web/icons').filter(name => name.endsWith('.svg'))) {
  icons[file.slice(0, -4)] = readFileSync(`web/icons/${file}`, 'utf8').replace(/<!--[^]*?-->/g, '').trim();
}
const html = readFileSync('web/index.html', 'utf8').replace('/*ICONS*/ {}', JSON.stringify(icons));
writeFileSync('include/web_page.h', `// Generated by tools/embed-web.mjs.\n#pragma once\n#include <Arduino.h>\nstatic const char WebPage[] PROGMEM = R"CARDTUNES(${html})CARDTUNES";\n`);
